k8s-engine: Simplify helm implementation
rancher-sandbox/rd pull request #107
Opened 2021-02-10 21:26 UTC by mook-as

Back in 56c06cba we implemented a helper method for uninstalling helm releases; we never got around to reusing the helper function for the other methods.  This makes us do that, reducing some repeated code.

2021-02-11 22:36 UTC, ericpromislow requested changes

2021-02-11 22:36 UTC, ericpromislow commented on src/k8s-engine/helm.js
> +    throw `Failed to list resource: ${err}`;
`Failed to list releases…` ?

2021-02-11 22:36 UTC, ericpromislow commented on src/k8s-engine/helm.js
> +    throw new Error(`Failed to get resource status: ${err}`);
`Failed to get status of release ${namespace ? namespace + ':' : ''}${name}: ${err}` ?

2021-02-11 22:36 UTC, ericpromislow commented on src/k8s-engine/helm.js
> +    throw new Error(`Failed to install chart: ${err}`);
Like before, I think we should include the name (and namespace) of an object that we fail to process in the error message.

2021-02-12 02:26 UTC, mook-as commented
- Rebased against master
- Added the namespace to error messages as appropriate
- Added tests.

2021-02-12 21:57 UTC, ericpromislow approved these changes

2021-02-13 00:07 UTC, merged