Adding contributing file
rancher-sandbox/rd pull request #186
Opened 2021-04-23 13:50 UTC by mattfarina

2021-04-23 22:13 UTC, ericpromislow requested changes
Ready for merging after fixing the typo

2021-04-23 22:13 UTC, ericpromislow commented on CONTRIBUTING.md
> +commit automaticallynwith `git commit -s`.
typo between `automatically` and `with`

2021-04-27 20:09 UTC, mattfarina commented on CONTRIBUTING.md
> +commit automaticallynwith `git commit -s`.
Thanks for catching that.

2021-04-27 20:09 UTC, mattfarina commented
This is ready to be re-reviewed

2021-04-27 21:14 UTC, ericpromislow approved these changes
LGTM

2021-04-27 21:48 UTC, merged